const $ = id => document.getElementById(id);
let task = null, busy = false, media = {products:[],avatar:''}, loadingImages = 0;
const settingsKey='shoeflow15-settings', draftKey='shoeflow15-draft';
function status(text){$('status').textContent=text;}
try{const s=JSON.parse(localStorage.getItem(settingsKey)||'{}');for(const id of ['endpoint','model','key'])$(id).value=s[id]||'';$('script').value=localStorage.getItem(draftKey)||'';}catch{status('浏览器设置无法恢复，请重新填写。');}
for(const id of ['endpoint','model','key'])$(id).addEventListener('change',()=>{try{localStorage.setItem(settingsKey,JSON.stringify(Object.fromEntries(['endpoint','model','key'].map(k=>[k,$(k).value]))));}catch{status('浏览器无法保存设置。');}});
$('script').addEventListener('input',()=>{try{localStorage.setItem(draftKey,$('script').value);}catch{}});
async function api(url,body){const res=await fetch(url,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await res.json();if(!res.ok)throw new Error(data.error||'请求失败');return data;}
async function copy(text){try{await navigator.clipboard.writeText(text);status('已复制完整提示词。');}catch{status('剪贴板不可用，请选中文本框内全部内容复制。');}}
function button(text,fn){const b=document.createElement('button');b.textContent=text;b.onclick=fn;return b;}
function show(t){task=t;media=t.references||{products:[],avatar:''};previewMedia();$('script').value=t.script;$('count').value=t.options?.productCount??1;$('avatar').value=t.options?.avatar===false?'no':'yes';$('mode').value=t.options?.mode||'reference';const out=$('results');out.replaceChildren();const bar=document.createElement('div');bar.className='toolbar';const title=document.createElement('strong');title.textContent=`${t.batches.length} 组 · 共 ${t.batches.reduce((n,b)=>n+b.duration,0)} 秒 · 已按任务保存`;bar.append(title,button('复制全部组',()=>copy(t.batches.map(b=>`【第${b.index}组】\n${b.prompt}`).join('\n\n'))),button('导出任务 JSON',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(t,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`提示词-${t.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}));out.append(bar);
for(const b of t.batches){const box=document.createElement('section');box.className='batch';const h=document.createElement('h2');h.textContent=`第 ${b.index} 组 · ${b.duration} 秒 · 分镜 ${b.startScene}–${b.endScene}`;h.append(button('复制本组完整提示词',()=>copy(b.prompt)));const refs=document.createElement('p');refs.className='refs';refs.textContent=b.references.map(r=>`图片${r.number}：${r.label}${r.role==='first_frame'?'（请设为首帧）':''}`).join('\n')||'本组无参考图';const text=document.createElement('textarea');text.readOnly=true;text.rows=14;text.value=b.prompt;box.append(h,refs,text);out.append(box);}
$('editor').hidden=false;$('board').value=JSON.stringify({globalStyle:t.globalStyle,continuityBible:t.continuityBible,scenes:t.scenes},null,2);}
async function history(){const list=await api('/api/tasks');$('history').replaceChildren();for(const t of list)$('history').append(button(`${t.title} · ${t.count}组`,async()=>{if(busy)return;try{show(await api('/api/tasks/'+t.id));status('已打开保存的任务。');}catch(e){status(e.message);}}));}
async function run(edit=false){if(busy||loadingImages)return;busy=true;$('generate').disabled=$('compile').disabled=true;status('正在整理分镜与提示词，请稍候…');try{const data={script:$('script').value,references:media,options:{productCount:Number($('count').value),avatar:$('avatar').value==='yes',mode:$('mode').value}};if(edit)data.board=JSON.parse($('board').value);else data.llm={endpoint:$('endpoint').value,key:$('key').value,model:$('model').value};show(await api(edit?'/api/compile':'/api/generate',data));await history();status('完成，已保存为独立任务。');}catch(e){status('未完成：'+e.message);}finally{busy=false;$('generate').disabled=$('compile').disabled=false;}}
$('generate').onclick=()=>run();$('compile').onclick=()=>run(true);$('fresh').onclick=()=>{if(busy)return;task=null;media={products:[],avatar:''};previewMedia();$('script').value='';$('results').replaceChildren();$('editor').hidden=true;status('输入新的口播文案即可。');};history().catch(e=>status(e.message));

function previewMedia(){const el=$('mediaPreview');el.replaceChildren();for(const [i,data] of [media.avatar,...media.products].entries()){if(!data)continue;const img=document.createElement('img');img.src=data;img.alt=i===0?'人物参考':`商品参考${i}`;img.style.cssText='width:90px;height:90px;object-fit:contain;margin:8px;border:1px solid #ddd';el.append(img);}const has=media.products.length||media.avatar;$('count').disabled=$('avatar').disabled=Boolean(has);if(has){$('count').value=media.products.length;$('avatar').value=media.avatar?'yes':'no';}}
async function readImages(files){return Promise.all([...files].map(file=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('请选择5MB以内的JPG、PNG或WEBP图片');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('图片读取失败'));reader.readAsDataURL(file);});}));}
for(const [id,kind] of [['products','products'],['portrait','avatar']])$(id).onchange=async()=>{if(busy)return;loadingImages++;$('generate').disabled=$('compile').disabled=true;try{const files=$(id).files;if(files.length>(kind==='products'?8:1))throw new Error('商品图最多8张，人物图最多1张');const values=await readImages(files);if(kind==='products')media.products=values;else media.avatar=values[0]||'';previewMedia();status('参考图已准备好，将随文案发给视觉模型。');}catch(e){status(e.message);}finally{loadingImages--;if(!loadingImages)$('generate').disabled=$('compile').disabled=busy;$(id).value='';}};
$('clearMedia').onclick=()=>{if(busy||loadingImages)return;media={products:[],avatar:''};previewMedia();status('已清空参考图。');};
